### PR TITLE
Inputs

### PR DESCRIPTION
**Pull request by VLeads**
Added Input component
Added code snippet
Done some minor fixes also.

### CODE REVIEW

**Comment by ArjunJunna** [comment]
everything is fine.

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me :) Just wanted to remind you that for P0 inputs we also have 
- textbox
- validation

**Review by vrinda-mahajan — APPROVED** [review]
LGTM👍

**Comment by animeshgarai09** [comment]
The code is clean. good job on UI.

**Comment by VLeads** [comment]
> Looks good to me :) Just wanted to remind you that for P0 inputs we also have
> 
> * textbox
> * validation

Oh, thanks! I will surely add them.

**Pull request merged**
